services:
  - type: web
    name: video-content-moderator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 10000
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: video-storage-3
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    build:
      includePaths:
        - models/
        - uploads/
    gunicorn:
      workerTimeout: 300
      workerClass: sync
      workers: 2
